# Generated by Django 3.0.5 on 2020-10-05 02:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compartment', '0002_auto_20201005_0213'),
        ('part', '0001_initial'),
        ('color', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='Quantity')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='color.ColorModel', verbose_name='Color Name')),
                ('compartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compartment.CompartmentModel', verbose_name='Compartment Name')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='part.PartModel', verbose_name='Part Name')),
            ],
        ),
    ]
