# Generated by Django 3.0.5 on 2020-10-05 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compartment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('compartment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='compartment.CompartmentModel')),
            ],
        ),
    ]
