# Generated by Django 3.0.5 on 2020-10-05 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ColorModel',
            fields=[
                ('color_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Color Name')),
                ('color_code', models.CharField(max_length=5, unique=True, verbose_name='Color Code')),
            ],
        ),
    ]
