# Generated by Django 3.0.5 on 2020-10-05 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompartmentModel',
            fields=[
                ('compartment_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='compartment name')),
                ('code', models.CharField(max_length=5, verbose_name='compartment code')),
            ],
        ),
    ]
