# Generated by Django 3.0.5 on 2020-10-05 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compartment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compartmentmodel',
            name='code',
            field=models.CharField(max_length=5, unique=True, verbose_name='compartment code'),
        ),
    ]
